### ISSUE TITLE
Option to set tabWidth

### ISSUE THREAD

**Issue by comanche** [yaeda/inkdrop-prettier#1]
Prettier should respect Inkdrop's tab width setting.

This is best explained with an example:

The default tab width is 2.

**1 - Create the following numbered list:**

```
1. aaa
  2. bbb # indent: 2 spaces (1 tab)
3. ccc
4. ddd
```

**2 - Save the changes and the 2 spaces is removed by prettier.**

```
1. aaa
2. bbb # indent: 0 space
3. ccc
4. ddd
```

**3 - Recreate the list in step 1 with 4 spaces**

```
1. aaa
    2. bbb # indent: 4 spaces (2 tabs)
3. ccc
4. ddd
```

**4 - Save the changes and the 4 spaces is changed to 3 spaces by prettier.**

```
1. aaa
   2. bbb # indent: 3 space
3. ccc
4. ddd
```

**5 - Change Indent Unit to 4 spaces in Inkdrop's Editing preference.**

## 6 - Set prettier `tabWidth` option to `4` manually.

```js
// lib/inkdrop-prettier.js
const format = () => {
  // ...
  const { formatted, cursorOffset } = prettier.formatWithCursor(beforeText, {
    cursorOffset: beforeOffset,
    parser: "markdown",
    tabWidth: 4 // <--- ADD THIS ---
  });
  // ...
}
```

**7 - Recreate the list in step 3 with 4 spaces**

```
1. aaa
    2. bbb # indent: 4 spaces (only 1 tab now)
3. ccc
4. ddd
```

**8 - Save and the 4 spaces are retained by prettier**

**NOTE:**  Keeping the default tab width of 2 and setting prettier's `tabWidth` to 2 gives the same result as in step 2.  More time needed to figure out why.

**Comment by yaeda** [comment]
@comanche Hi, thank you for your improvement idea.
Ideally, I think the formatter should use Inkdrops's setting value directly.
I have created a question on the forum to achieve it.
> [Can plugin read indent unit setting value? \- 💁🏻‍♂️Support \- Inkdrop Forum](https://forum.inkdrop.app/t/can-plugin-read-indent-unit-setting-value/2030)

**Comment by yaeda** [comment]
@comanche released v1.1.0, please try it.

**Comment by comanche** [comment]
Looks like your fix should fix the problem.  Unfortunately, I've updated to Inkdrop 5 recently and I'm seeing the following:

**Indent Unit:** `2`

Create these lists:

```
- aaa
  - bbb # indent: 2 spaces
- ccc
- ddd
- eee

1. aaa
  2. bbb # indent: 2 spaces
3. ccc
4. ddd
5. eee
```

On save, I see:

```
- aaa
  - bbb # indent: 2 spaces
- ccc
- ddd
- eee

1. aaa
2. bbb # indent: 2 spaces
3. ccc
4. ddd
5. eee
```

Repeat the same with **Indent Unit:** `4`.

```
- aaa
    - bbb # indent: 4 spaces
- ccc
- ddd
- eee

1. aaa
    2. bbb # indent: 4 spaces
3. ccc
4. ddd
5. eee
```

On save, I see:
- The unordered bullet list have three spaces between the bullet and the first letter.  This behavior is not consistent as there is only one space between the period and the first letter in the ordered numbered list.
- The second item in the ordered numbered list is now part of the first item.

```
-   aaa
    -   bbb # indent: 4 spaces
-   ccc
-   ddd
-   eee

1. aaa 2. bbb # indent: 4 spaces
2. ccc
3. ddd
4. eee
```

**Comment by yaeda** [comment]
@comanche It seems to be a prettier’s issue.
Please take a look at the demo and issue below

- [Prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAQ2wHSug9DAI1LwzEvPQBM7q5G88BGAOi130ICYPTieAMwdKYPABYOdGngCsHRnBAAaEBAAOMAJbQAzslCYATsYgB3AAomEBlJgA25zAE8Da4scxgA1nBgAyhre2lAA5sgwxgCucGpwALbEcHQpADKY4dGYYXAAYhDGCZgwOuHIIJjRMBCqIAAWMAkOAOr12vB6wWBwAbYd2gBuHS4VYHruIKF6cMYwll5hxcgAZo4zagBWegAeAEJevv4BmAlwaaHKSGsOGyDbOwGhYQ5wAIrREPCr63EgwcYZsYKsVjD4aBYoHUNMZQjAWtoaDB6sgABwABjUMIgMxaXg0FRhcCBg2UagAjp94AtNHZKnpUFBGDQUnVjHBKdp2Qscstrr81DMEtpIjE-npnq8Pl8rjc7jBMMQEUiUUgJGoophtA5ngBhCAJPkgYlyOrRGYAFUVdjlf0GsQAklAWbAAmBYVoAILOgIwFyvH63OAAX2DQA)
- prettier/prettier#5019

**Comment by comanche** [comment]
Thanks for the update.  Hopefully it'll get fixed soon.

**Comment by yaeda** [comment]
I will keep watching prettier's update.
