### ISSUE TITLE
Option to preserve 4 dashes?

### ISSUE THREAD

**Issue by ryanpcmcquen** [yaeda/inkdrop-prettier#2]
Hi there! Thanks for this awesome plugin. I love having formatting on save for Markdown, it really helps a lot. Is there a way to preserve 4 dashes?

I use [`reveal-md-presenter`](https://github.com/skipadu/reveal-md-presenter) and it makes a vertical slide with 4 dashes, but Prettier always sets that back to 3.

**Comment by yaeda** [comment]
@ryanpcmcquen Sorry for my late reply.

The default prettier doesn't support it. I couldn't even find a custom parser to support it.

It`s very messy, but I think you can use the following workarounds.

```
<!-- prettier-ignore -->
<!-- prettier-ignore -->
----
```
